version: "3.9"

services:
  frontend:
    container_name: frontend-angular
    build:
      context: ./Stack-mean/frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./Stack-mean/frontend:/app
    depends_on:
      - backend

  backend:
    container_name: backend-node
    build:
      context: ./Stack-mean/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Stack-mean/backend:/app
    environment:
      - NODE_ENV=development
      - DATABASE_NAME=mydatabase
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=
